config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'

  get '/users/sign_out'
  get '/users/sign_in'

  resources :products
  root 'page#home'
  # root 'welcome#index'

  get 'page/about'

  get 'page/faqs'

  get 'page/contact'

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  before_action :authenticate_user!, except: [:index]

  def add
    id = params[:id]
      if session[:cart] then  # if a cart has already been created, use it, otherwise make a new one
        cart = session[:cart]
      else
        session[:cart] = {}
        cart = session[:cart]
      end

      if cart[id] then        # if the product has been added to the cart, then increase by 1.
        cart[id] = cart[id] + 1
      else
        cart[id] = 1
      end
    redirect_to :action => :index
  end

  def clearCart
    session[:cart] = nil
    redirect_to :action => :index
  end


  # def minusCart I have to confess, I couldn't figure this action out. I will. I want to take items off
  #   if cart[id] then         if the product has been added to the cart, then subtract by 1.
  #     cart[id] = cart[id] -= 1
  #   end
  #
  # end


  def index #when user goes to the /cart then the cart should be empty or full of some product.
    @product = Product
    if session[:cart] then
      @cart = session[:cart]
    else
      @cart = {}
    end
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  before_action :authenticate_user!, except: [:home, :about, :faqs]
  # another way of doing above line is: before_action :authenticate_user!, only: [:faqs]
  # but it all depends on your preference and how much clean code you want to write
  def home
  end

  def about
  end

  def faqs
  end

  def contact
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :brand, :model, :sku, :price, :desc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cart/index.html.erb
<h1>Your Cart</h1>

<% if @cart.empty? %> <!-- If cart is empty, it will say so -->
  <p>Your cart is currently empty.</p>
<% else %>
<%= link_to 'Empty Your Cart', cart_clear_path %> <!-- A link to a cart controller action cartClear which will empty out your cart  -->
<% end %>
<br></br><br></br>

<% total = 0 %>
<ul id="list">
<% @cart.each do | id, quantity | %>
    <% product = Product.find_by_id(id) %>

  <li>
      <p>Name: <%= link_to product.name, product %></p>
      <p>Brand: <%= product.brand %></p>
      <p>Model: <%= product.model %></p>
      <p>Price: <%= number_to_currency(product.price, :unit => '$' )%></p>
      <p>Quantity: <%= quantity %></p>
  </li>
  <% total += quantity * product.price %> <!-- As you add items to this cart, the total will be calcuated, otherwise refer to line 10-->
<% end %>

<p><b><%= number_to_currency(total, :unit => '$')%></b></p> <!-- making this column from integer into something befitting currency -->
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cartapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="icon" href="../../favicon.ico">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>

<nav id="nav">
  <div id="page_nav">
    <%= link_to "Home", root_path %>
    <%= link_to "Shop", products_path %>
    <%= link_to "About", page_about_path %>
    <%= link_to "FAQs", page_faqs_path %>
    <%= link_to "Contact", page_contact_path %>
  </div>

<!-- the signin logic is so that both links don't appear at once. If you're already signed in, you shouldn't see a sign in link -->

  <div id="sign_in">
    <% if user_signed_in? %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path %>
      <%= link_to "Sign Up", new_user_registration_path %>
    <% end %>
  </div>
</nav>

<div id="main_wrap">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
</div>
</body>
</html>

app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/page/contact.html.erb
<h1>Page#contact</h1>
<p>Find me in app/views/page/contact.html.erb</p>

app/views/page/faqs.html.erb
<h1>Page#faqs</h1>
<p>Find me in app/views/page/faqs.html.erb</p>

app/views/page/home.html.erb
<h1>Welcome to CartApp!</h1>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :sku %><br>
    <%= f.text_field :sku %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Products</h1>
<%= link_to 'New Product', new_product_path %>
<div class="container">
  <% @products.each do |product| %>
  <div class="col-md-4">
    <ul>
      <!-- Trigger the modal with a button -->
      <li><button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button></li>
      <br></br>
      <li><b>Name:</b> <%= product.name %></li>
      <li><b>Brand:</b> <%= product.brand %></li>
      <li><b>Model:</b> <%= product.model %></li>
      <li><b>Price:</b> <%= product.price %></li>
      <!-- <li><%= link_to 'Edit', edit_product_path(product) %></li>
      <li><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      <li><a href="/cart/<%= product.id %>"> Add to Cart </a></li> -->
      <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title"><%= product.name %></h4>
            </div>
            <div class="modal-body">
              <p><b>Brand:</b> <%= product.brand %></p>
              <p><b>Model:</b> <%= product.model %></p>
              <p><b>Price:</b> <%= product.price %></p>
              <p><b>SKU:</b> <%= product.sku %></p>
              <p><b>DESC:</b> <%= product.desc %></p>
              <li><%= link_to 'Edit', edit_product_path(product) %></li>
              <li><%= link_to 'Delete Items', product, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              <li><a href="/cart/<%= product.id %>"> Add to Cart </a></li>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>

        </div>
      </div>
      <!-- <li><b>Name:</b> <%= product.name %></li>
      <li><b>Brand:</b> <%= product.brand %></li>
      <li><b>Model:</b> <%= product.model %></li>
      <li><b>Price:</b> <%= product.price %></li>
      <li><b>SKU:</b> <%= product.sku %></li>
      <li><b>DESC:</b> <%= product.desc %></li>
      <li><%= link_to 'Show', product %></li>
      <li><%= link_to 'Edit', edit_product_path(product) %></li>
      <li><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      <li><a href="/cart/<%= product.id %>"> Add to Cart </a></li> -->
    </ul>

  </div>
    <% end %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<h1>THIS IS MY PRODUCT</h1>
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Model:</strong>
  <%= @product.model %>
</p>

<p>
  <strong>Sku:</strong>
  <%= @product.sku %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @product.desc %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>